"""initial p0 schema

Revision ID: 20260818_0001
Revises: 
Create Date: 2026-08-18 16:39:58.956539
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '20260818_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_companies_code')
    )
    op.create_table('compliance_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_compliance_rules_effective_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', 'version', name='uq_compliance_rules_code_version')
    )
    op.create_index('ix_compliance_rules_active_dates', 'compliance_rules', ['is_active', 'effective_from', 'effective_to'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('WORKER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_code', name='uq_users_company_employee'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_company_role_active', 'users', ['company_id', 'role', 'is_active'], unique=False)
    op.create_table('work_sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Seoul', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name='ck_work_sites_latitude'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name='ck_work_sites_longitude'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_work_sites_company_name')
    )
    op.create_index('ix_work_sites_company_active', 'work_sites', ['company_id', 'is_active'], unique=False)
    op.create_table('site_weather_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('KMA_API', 'MANUAL', 'DEMO', name='weather_source'), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('wind_speed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('feels_like_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('humidity BETWEEN 0 AND 100', name='ck_site_weather_logs_humidity'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_site_weather_logs_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_site_weather_logs_longitude'),
    sa.ForeignKeyConstraint(['site_id'], ['work_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_site_weather_logs_site_measured_at', 'site_weather_logs', ['site_id', sa.literal_column('measured_at DESC')], unique=False)
    op.create_table('work_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='work_session_status'), server_default='IN_PROGRESS', nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('work_intensity', sa.String(length=30), nullable=False),
    sa.Column('clothing_level', sa.String(length=30), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'IN_PROGRESS' AND ended_at IS NULL) OR (status = 'COMPLETED' AND ended_at IS NOT NULL)", name='ck_work_sessions_status_ended_at'),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='ck_work_sessions_time_order'),
    sa.ForeignKeyConstraint(['site_id'], ['work_sites.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_work_sessions_site_status', 'work_sessions', ['site_id', 'status'], unique=False)
    op.create_index('ix_work_sessions_worker_started_at', 'work_sessions', ['worker_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('uq_work_sessions_active_worker', 'work_sessions', ['worker_id'], unique=True, postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.create_table('worker_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_site_id', sa.Uuid(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('has_cooling_device', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age IS NULL OR age BETWEEN 18 AND 100', name='ck_worker_profiles_age'),
    sa.ForeignKeyConstraint(['assigned_site_id'], ['work_sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_worker_profiles_assigned_site', 'worker_profiles', ['assigned_site_id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_session_id', sa.Uuid(), nullable=False),
    sa.Column('weather_log_id', sa.Uuid(), nullable=False),
    sa.Column('compliance_rule_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NORMAL', 'REST_SCHEDULED', 'DEADLINE_IMMINENT', 'IMMEDIATE_REST_REQUIRED', name='compliance_status'), nullable=False),
    sa.Column('is_rest_required', sa.Boolean(), nullable=False),
    sa.Column('rest_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('required_rest_minutes', sa.Integer(), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_rest_minutes IS NULL OR required_rest_minutes >= 0', name='ck_compliance_checks_required_rest_minutes'),
    sa.ForeignKeyConstraint(['compliance_rule_id'], ['compliance_rules.id'], ),
    sa.ForeignKeyConstraint(['weather_log_id'], ['site_weather_logs.id'], ),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_checks_status_evaluated_at', 'compliance_checks', ['status', sa.literal_column('evaluated_at DESC')], unique=False)
    op.create_index('ix_compliance_checks_work_session_evaluated_at', 'compliance_checks', ['work_session_id', sa.literal_column('evaluated_at DESC')], unique=False)
    op.create_table('heat_risk_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_session_id', sa.Uuid(), nullable=False),
    sa.Column('weather_log_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_core_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'CAUTION', 'HIGH', name='ai_risk_level'), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('main_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score IS NULL OR risk_score >= 0', name='ck_heat_risk_assessments_risk_score'),
    sa.ForeignKeyConstraint(['weather_log_id'], ['site_weather_logs.id'], ),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heat_risk_assessments_model_version', 'heat_risk_assessments', ['model_version'], unique=False)
    op.create_index('ix_heat_risk_assessments_risk_level_evaluated_at', 'heat_risk_assessments', ['risk_level', sa.literal_column('evaluated_at DESC')], unique=False)
    op.create_index('ix_heat_risk_assessments_work_session_evaluated_at', 'heat_risk_assessments', ['work_session_id', sa.literal_column('evaluated_at DESC')], unique=False)
    op.create_table('rest_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_session_id', sa.Uuid(), nullable=False),
    sa.Column('rest_type', sa.Enum('LEGAL_REQUIRED', 'AI_RECOMMENDED', 'SELF_INITIATED', name='rest_type'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='ck_rest_records_time_order'),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rest_records_work_session_started_at', 'rest_records', ['work_session_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('uq_rest_records_active_work_session', 'rest_records', ['work_session_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_rest_records_active_work_session', table_name='rest_records', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index('ix_rest_records_work_session_started_at', table_name='rest_records')
    op.drop_table('rest_records')
    op.drop_index('ix_heat_risk_assessments_work_session_evaluated_at', table_name='heat_risk_assessments')
    op.drop_index('ix_heat_risk_assessments_risk_level_evaluated_at', table_name='heat_risk_assessments')
    op.drop_index('ix_heat_risk_assessments_model_version', table_name='heat_risk_assessments')
    op.drop_table('heat_risk_assessments')
    op.drop_index('ix_compliance_checks_work_session_evaluated_at', table_name='compliance_checks')
    op.drop_index('ix_compliance_checks_status_evaluated_at', table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index('ix_worker_profiles_assigned_site', table_name='worker_profiles')
    op.drop_table('worker_profiles')
    op.drop_index('uq_work_sessions_active_worker', table_name='work_sessions', postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.drop_index('ix_work_sessions_worker_started_at', table_name='work_sessions')
    op.drop_index('ix_work_sessions_site_status', table_name='work_sessions')
    op.drop_table('work_sessions')
    op.drop_index('ix_site_weather_logs_site_measured_at', table_name='site_weather_logs')
    op.drop_table('site_weather_logs')
    op.drop_index('ix_work_sites_company_active', table_name='work_sites')
    op.drop_table('work_sites')
    op.drop_index('ix_users_company_role_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_compliance_rules_active_dates', table_name='compliance_rules')
    op.drop_table('compliance_rules')
    op.drop_table('companies')
    postgresql.ENUM(name='rest_type').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='ai_risk_level').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='compliance_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='work_session_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='weather_source').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='user_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
