"""phase1 auth: employee roster, numeric display_id, worker profile fields

Revision ID: 23d7ad564b27
Revises: b91b78b30726
Create Date: 2026-08-19 00:15:24.276039
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



revision: str = '23d7ad564b27'
down_revision: Union[str, Sequence[str], None] = 'b91b78b30726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_rosters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', postgresql.ENUM('WORKER', 'ADMIN', name='user_role', create_type=False), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('workplace_site_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['workplace_site_id'], ['work_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code', name='uq_employee_rosters_employee_code')
    )
    op.create_index('ix_employee_rosters_employee_code_name', 'employee_rosters', ['employee_code', 'name'], unique=False)
    op.add_column('users', sa.Column('display_id', sa.Integer(), sa.Identity(always=False), nullable=False))
    op.drop_constraint(op.f('uq_users_company_employee'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_display_id', 'users', ['display_id'])
    op.create_unique_constraint('uq_users_employee_code', 'users', ['employee_code'])
    gender_enum = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender')
    gender_enum.create(op.get_bind(), checkfirst=True)
    work_intensity_enum = postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='work_intensity')
    work_intensity_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('worker_profiles', sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender', create_type=False), nullable=True))
    op.add_column('worker_profiles', sa.Column('job_type', sa.String(length=100), nullable=True))
    op.add_column('worker_profiles', sa.Column('work_intensity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='work_intensity', create_type=False), server_default='MEDIUM', nullable=False))
    op.add_column('worker_profiles', sa.Column('ppe_worn', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'ppe_worn')
    op.drop_column('worker_profiles', 'work_intensity')
    op.drop_column('worker_profiles', 'job_type')
    op.drop_column('worker_profiles', 'gender')
    postgresql.ENUM(name='work_intensity').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='gender').drop(op.get_bind(), checkfirst=True)
    op.drop_constraint('uq_users_employee_code', 'users', type_='unique')
    op.drop_constraint('uq_users_display_id', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_company_employee'), 'users', ['company_id', 'employee_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'display_id')
    op.drop_index('ix_employee_rosters_employee_code_name', table_name='employee_rosters')
    op.drop_table('employee_rosters')
    # ### end Alembic commands ###
