"""phase2 worker: rest_records rework, notifications, display_id for sessions

Revision ID: 60a15d5e39bd
Revises: 23d7ad564b27
Create Date: 2026-08-19 01:06:33.943699
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '60a15d5e39bd'
down_revision: Union[str, Sequence[str], None] = '23d7ad564b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('REST_RECOMMENDATION', 'ADMIN_REST_REQUEST', 'WORK_STARTED', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('risk_level', sa.Enum('NORMAL', 'WATCH', 'CAUTION', 'HIGH', name='overall_risk_level'), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_id')
    )
    op.create_index('ix_notifications_user_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    rest_reason_enum = postgresql.ENUM('USER_STARTED', 'SYSTEM_RECOMMENDED', 'ADMIN_REQUESTED', name='rest_reason')
    rest_reason_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('rest_records', sa.Column('display_id', sa.Integer(), sa.Identity(always=False), nullable=False))
    op.add_column('rest_records', sa.Column('worker_id', sa.Uuid(), nullable=False))
    op.add_column('rest_records', sa.Column('reason', postgresql.ENUM('USER_STARTED', 'SYSTEM_RECOMMENDED', 'ADMIN_REQUESTED', name='rest_reason', create_type=False), nullable=False))
    op.add_column('rest_records', sa.Column('target_minutes', sa.Integer(), nullable=False))
    op.add_column('rest_records', sa.Column('resume_work_after_rest', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('rest_records', 'work_session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_rest_records_worker_started_at', 'rest_records', ['worker_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('uq_rest_records_active_worker', 'rest_records', ['worker_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL AND work_session_id IS NULL'))
    op.create_unique_constraint(None, 'rest_records', ['display_id'])
    op.create_foreign_key(None, 'rest_records', 'users', ['worker_id'], ['id'])
    op.drop_column('rest_records', 'rest_type')
    postgresql.ENUM(name='rest_type').drop(op.get_bind(), checkfirst=True)
    op.add_column('work_sessions', sa.Column('display_id', sa.Integer(), sa.Identity(always=False), nullable=False))
    op.create_unique_constraint(None, 'work_sessions', ['display_id'])
    op.add_column('worker_profiles', sa.Column('notifications_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'notifications_enabled')
    op.drop_constraint(None, 'work_sessions', type_='unique')
    op.drop_column('work_sessions', 'display_id')
    op.add_column('rest_records', sa.Column('rest_type', postgresql.ENUM('LEGAL_REQUIRED', 'AI_RECOMMENDED', 'SELF_INITIATED', name='rest_type'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rest_records', type_='foreignkey')
    op.drop_constraint(None, 'rest_records', type_='unique')
    op.drop_index('uq_rest_records_active_worker', table_name='rest_records', postgresql_where=sa.text('ended_at IS NULL AND work_session_id IS NULL'))
    op.drop_index('ix_rest_records_worker_started_at', table_name='rest_records')
    op.alter_column('rest_records', 'work_session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('rest_records', 'resume_work_after_rest')
    op.drop_column('rest_records', 'target_minutes')
    op.drop_column('rest_records', 'reason')
    postgresql.ENUM(name='rest_reason').drop(op.get_bind(), checkfirst=True)
    op.drop_column('rest_records', 'worker_id')
    op.drop_column('rest_records', 'display_id')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index('ix_notifications_user_created_at', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
