"""phase3 admin: alerts, admin_settings tables

Revision ID: 99e5f9339c47
Revises: 60a15d5e39bd
Create Date: 2026-08-19 01:21:42.162085
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



revision: str = '99e5f9339c47'
down_revision: Union[str, Sequence[str], None] = '60a15d5e39bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('apparent_temp_danger_c', sa.Numeric(precision=5, scale=2), server_default='43.0', nullable=False),
    sa.Column('apparent_temp_caution_c', sa.Numeric(precision=5, scale=2), server_default='38.0', nullable=False),
    sa.Column('max_work_minutes', sa.Integer(), server_default='120', nullable=False),
    sa.Column('rest_minutes', sa.Integer(), server_default='20', nullable=False),
    sa.Column('core_temp_caution_c', sa.Numeric(precision=5, scale=2), server_default='37.5', nullable=False),
    sa.Column('core_temp_danger_c', sa.Numeric(precision=5, scale=2), server_default='38.0', nullable=False),
    sa.Column('default_site', sa.String(length=50), server_default='all', nullable=False),
    sa.Column('channel_push', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('channel_sms', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('channel_email', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('channel_emergency', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_admin_settings_company')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('risk_level', postgresql.ENUM('NORMAL', 'WATCH', 'CAUTION', 'HIGH', name='overall_risk_level', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('status_text', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('apparent_temp_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_core_temp_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status'), server_default='OPEN', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_id')
    )
    op.create_index('ix_alerts_status_occurred_at', 'alerts', ['alert_status', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('ix_alerts_worker_occurred_at', 'alerts', ['worker_id', sa.literal_column('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_worker_occurred_at', table_name='alerts')
    op.drop_index('ix_alerts_status_occurred_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
