"""drop wind_speed from site_weather_logs

Revision ID: b91b78b30726
Revises: 20260818_0001
Create Date: 2026-08-18 23:21:05.157289
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'b91b78b30726'
down_revision: Union[str, Sequence[str], None] = '20260818_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_weather_logs', 'wind_speed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_weather_logs', sa.Column('wind_speed', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
